[package]
name = "bastille-rs"
version = "0.1.0"
authors = ["blueslimee <blueslimexdfodeu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.9.1"
actix-web = "2.0"
actix-rt = "1.0"