name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup dependencies
      run: ./setup.sh
    - name: Run CMake
      uses: lukka/run-cmake@v3
      id: runcmake
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'